/*
CONTA A QUANTIDADE DE REGISTRO NA COLUNA FIRSTNAME
CONTA A QUANTIDADE DE REGISTROS DISTINTOS NA COLUNA FIRSTNAME
DEPOIS FAZ UMA SUBTRAÇÃO DAS DUAS CONTAGENS
*/
SELECT (COUNT(FirstName)-COUNT(DISTINCT FirstName))
FROM Person.Person
/*
RETORNA O MENOR E O MAIOR NOME DA COLUNA FIRSTNAME
*/
SELECT TOP 1
       FirstName,
       LEN(FirstName) AS [QUANTIDADE DE LETRAS]
  FROM PERSON.Person
  ORDER BY LEN(FirstName), FirstName;
  
SELECT TOP 1
       FirstName,
       LEN(FirstName) AS [QUANTIDADE DE LETRAS]
  FROM PERSON.Person
  ORDER BY LEN(FirstName) DESC;    